from setuptools import setup
import os.path as op
import glob
from setuptools.command.build_py import build_py


class build_py_with_references(build_py):
    def run(self):
        references_src = op.join("docs", "source", "references.bib")
        references_dst = op.join("AFQ", "_references.bib")

        with open(references_src) as f:
            references = f.read()

        references = """
#######################################################################
## AUTOGENERATED FILE. DO NOT EDIT. ##
## This file is generated from docs/source/references.bib ##
#######################################################################
""" + references

        with open(references_dst, "w") as f:
            f.write(references)

        super().run()

opts = dict(
    scripts=[op.join('bin', op.split(f)[-1]) for f in glob.glob('bin/*')],
    cmdclass={"build_py": build_py_with_references},
    package_data={
        "AFQ": ["_references.bib"],
    })


if __name__ == '__main__':
    setup(**opts)
