from setuptools import setup
import string
import os.path as op
import glob
from setuptools_scm import get_version
from setuptools.command.build_py import build_py


def local_version(version):
    """
    Patch in a version that can be uploaded to test PyPI
    """
    scm_version = get_version()
    if "dev" in scm_version:
        gh_in_int = []
        for char in version.node:
            if char.isdigit():
                gh_in_int.append(str(char))
            else:
                gh_in_int.append(str(string.ascii_letters.find(char)))
        return "".join(gh_in_int)
    else:
        return ""

class build_py_with_references(build_py):
    def run(self):
        references_src = op.join("docs", "source", "references.bib")
        references_dst = op.join("AFQ", "_references.bib")

        with open(references_src) as f:
            references = f.read()

        references = """
#######################################################################
## AUTOGENERATED FILE. DO NOT EDIT. ##
## This file is generated from docs/source/references.bib ##
#######################################################################
""" + references

        with open(references_dst, "w") as f:
            f.write(references)

        super().run()

opts = dict(
    use_scm_version={"root": ".", "relative_to": __file__,
                     "write_to": op.join("AFQ", "version.py"),
                     "local_scheme": local_version},
    scripts=[op.join('bin', op.split(f)[-1]) for f in glob.glob('bin/*')],
    cmdclass={"build_py": build_py_with_references},
    package_data={
        "AFQ": ["_references.bib"],
    })


if __name__ == '__main__':
    setup(**opts)
